service: ynab-stock-update

provider:
  name: aws
  region: eu-west-1
  runtime: nodejs8.10
  timeout: 5
  versionFunctions: false
  environment:
    YNAB_API_TOKEN: ${file(serverless.env.yml):YNAB_API_TOKEN, env:YNAB_API_TOKEN}
    AUTOMATIC_APPROVAL: ${file(serverless.env.yml):AUTOMATIC_APPROVAL, env:AUTOMATIC_APPROVAL}

custom:
  alerts:
    topics:
      alarm:
        topic: ${self:service}-alerts-alarm
        notifications:
          - protocol: email
            endpoint: ${file(serverless.env.yml):ALARM_EMAIL, env:ALARM_EMAIL}
    definitions:
      functionErrors:
        period: 86400 # 1 day
        treatMissingData: notBreaching
    alarms:
      - functionErrors

functions:
  ynab-stock-update:
    handler: src/index.run
    events:
      - schedule: cron(0 23 ? * 2-6 *)

plugins:
  - serverless-plugin-aws-alerts
